force-app/main/default/objects/Car__c/fields/Weight__c.field-meta.xml
<CustomField>
    <fullName>Weight__c</fullName>
    <label>Weight</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/formula-force/CarSelector.cls
/**
 * Created by Brooks Johnson - Insulet on 2/2/23.
 */

public with sharing class CarSelector extends fflib_SObjectSelector{

    public List<Schema.SObjectField> getSObjectFieldList(){
        return new List<Schema.SObjectField> {
                Car__c.Id,
                Car__c.Name,
                Car__c.Weight__c
        };
    }

    public Schema.SObjectType getSObjectType(){
        return Car__c.SObjectType;
    }

}