force-app/main/default/objects/ChampionshipPoints__mdt/fields/Points_Awarded__c.field-meta.xml
<CustomField>
    <fullName>Points_Awarded__c</fullName>
    <label>Points Awarded</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contestant__c/Contestant__c.object-meta.xml
<CustomObject>
    <label>Contestant</label>
    <nameField>
        <displayFormat>CONTEST-{00000000}</displayFormat>
        <label>Contestant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contestants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contestant__c/fields/Driver__c.field-meta.xml
<CustomField>
    <fullName>Driver__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Driver</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Only active drivers can be contestants in a race</errorMessage>
        <filterItems>
            <field>Driver__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <infoMessage>Only drivers whos status is active are permitted</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Driver__c</referenceTo>
    <relationshipLabel>Contestants</relationshipLabel>
    <relationshipName>Contestants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contestant__c/fields/Race__c.field-meta.xml
<CustomField>
    <fullName>Race__c</fullName>
    <label>Race</label>
    <referenceTo>Race__c</referenceTo>
    <relationshipLabel>Contestants</relationshipLabel>
    <relationshipName>Contestants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Driver__c/Driver__c.object-meta.xml
<CustomObject>
    <label>Driver</label>
    <nameField>
        <label>Driver Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Drivers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Race__c/Race__c.object-meta.xml
<CustomObject>
    <label>Race</label>
    <nameField>
        <label>Race Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Races</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Race__c/fields/Race__c.field-meta.xml
<CustomField>
    <fullName>Race__c</fullName>
    <label>Race</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
                <default>true</default>
                <label>Scheduled</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Red Flagged</fullName>
            </value>
            <value>
                <fullName>Finished</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/formula-force/Contestants.cls
/**
 * Created by Brooks Johnson - Insulet on 1/31/23.
 */

public inherited sharing class Contestants extends ApplicationDomain{

    public Contestants(List<Contestant__c> contestants){
        super(contestants);
    }

    public override void onValidate(){
        Set<Id> raceIds = new Set<Id>();
        for (Contestant__c contestant : (List<Contestant__c>)Records){
            raceIds.add(contestant.Race__c);
        }
        Map<Id, Race__c> associatedRaces = new Map<Id, Race__c>(new RaceSelector().selectById(raceIds));

        for (Contestant__c contestant : (List<Contestant__c>)Records){
            Race__c race = associatedRaces.get(contestant.Race__c);
            if (race.Status__c != 'Scheduled') {
                contestant.addError('Contestants can only be added to scheduled races');
            }
        }
    }

    public override void onValidate(Map<Id, SObject>existingRecords){
       List<Contestant__c> changedDrivers = getChangedRecords(new Set<SObjectField>{Contestant__c.Driver__c});
        Map<Id, Race__c> associatedRaces = queryAssociatedRaces(changedDrivers);
        for (Contestant__c contestant : changedDrivers){
            Race__c contestantRace = associatedRaces.get(contestant.Race__c);
            if (contestantRace.Status__c != 'Scheduled') {
                contestant.Driver__c.addError('You can only change drivers for scheduled races');
            }
        }
    }

    private Map<Id, Race__c> queryAssociatedRaces(List<Contestant__c> changedDrivers){
        Set<Id> raceIds = new Set<Id>();
        for (Contestant__c contestant : changedDrivers){
            raceIds.add(contestant.Race__c);
        }
        return new Map<Id, Race__c>(new RaceSelector().selectById(raceIds));

    }
    public class Constructor implements fflib_SObjectDomain.IConstructable {
        public fflib_SObjectDomain construct(List<SObject> sObjectList) {
            return new Contestants(sObjectList);
        }
    }
    public void awardChampionshipPoints(fflib_ISObjectUnitOfWork uow){
        Map<Integer, ChampionshipPoints__mdt> pointsByTrackPosition =
                new ChampionshipPointsSelector().pointsByTrackPosition();
        for (Contestant__c contestant : (List<Contestant__c>)Records){
            ChampionshipPoints__mdt pointsForPosition = pointsByTrackPosition.get(Integer.valueOf(contestant.RacePosition__c));
            if (pointsForPosition != null) {
                contestant.ChampionshipPoints__c = pointsForPosition.Points_Awarded__c;
                uow.registerDirty(contestant);
            }
        }
    }

}