force-app/main/default/objects/Contestant__c/Contestant__c.object-meta.xml
<CustomObject>
    <label>Contestant</label>
    <nameField>
        <displayFormat>CONTEST-{00000000}</displayFormat>
        <label>Contestant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contestants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contestant__c/fields/Driver__c.field-meta.xml
<CustomField>
    <fullName>Driver__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Driver</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Only active drivers can be contestants in a race</errorMessage>
        <filterItems>
            <field>Driver__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <infoMessage>Only drivers whos status is active are permitted</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Driver__c</referenceTo>
    <relationshipLabel>Contestants</relationshipLabel>
    <relationshipName>Contestants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contestant__c/fields/Race__c.field-meta.xml
<CustomField>
    <fullName>Race__c</fullName>
    <label>Race</label>
    <referenceTo>Race__c</referenceTo>
    <relationshipLabel>Contestants</relationshipLabel>
    <relationshipName>Contestants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Driver__c/Driver__c.object-meta.xml
<CustomObject>
    <label>Driver</label>
    <nameField>
        <label>Driver Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Drivers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Race__c/Race__c.object-meta.xml
<CustomObject>
    <label>Race</label>
    <nameField>
        <label>Race Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Races</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Race__c/fields/Race__c.field-meta.xml
<CustomField>
    <fullName>Race__c</fullName>
    <label>Race</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
                <default>true</default>
                <label>Scheduled</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Red Flagged</fullName>
            </value>
            <value>
                <fullName>Finished</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Race__c/fields/Season__c.field-meta.xml
<CustomField>
    <fullName>Season__c</fullName>
    <label>Season</label>
    <referenceTo>Season__c</referenceTo>
    <relationshipLabel>Races</relationshipLabel>
    <relationshipName>Races</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/RaceData__c/RaceData__c.object-meta.xml
<CustomObject>
    <label>Race Data</label>
    <nameField>
        <displayFormat>RDID-{0000000000}</displayFormat>
        <label>Race Data Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Race Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Season__c/Season__c.object-meta.xml
<CustomObject>
    <label>Season</label>
    <nameField>
        <label>Season Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Seasons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/formula-force/FormulaForceApplication.cls
/**
 * Created by bjohnson on 1/23/23.
 */

public with sharing class FormulaForceApplication {

    public static final fflib_Application.UnitOfWorkFactory unitOfWork =
            new fflib_Application.UnitOfWorkFactory(
                    new List<SObjectType>{
                            Driver__c.SObjectType,
                            Season__c.SObjectType,
                            Race__c.SObjectType,
                            Contestant__c.SObjectType
                    }

            );

    public static final fflib_Application.DomainFactory domain =
            new fflib_Application.DomainFactory(FormulaForceApplication.selector,
                    new Map<SObjectType, Type> {
                            Team__c.SObjectType => Teams.Constructor.class,
                            RaceData__c.SObjectType => Races.Constructor.class,
                            Car__c.SObjectType => Cars.Constructor.class,
                            Driver__c.SObjectType => Drivers.Constructor.class,
                            Contestant__c.SObjectType => Contestants.Constructor.class
                    }
            );

    public static final fflib_Application.ServiceFactory service =
            new fflib_Application.ServiceFactory(new Map<Type, Type>{
                    RaceService.class => RaceServiceImpl.class
            });

    public static final fflib_Application.SelectorFactory selector =
            new fflib_Application.SelectorFactory(
                    new Map<SObjectType, Type>{
                            Contestant__c.SObjectType => ContestantSelector.class
                    }
            );

            public static void throwAuraHandledException(Exception e){
                String message = e.getMessage();
                AuraHandledException error = new AuraHandledException(message);
                error.setMessage(message);
                throw error;
            }

}