force-app/main/default/objects/Race__c/Race__c.object-meta.xml
<CustomObject>
    <label>Race</label>
    <nameField>
        <label>Race Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Races</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Race__c/fields/Race__c.field-meta.xml
<CustomField>
    <fullName>Race__c</fullName>
    <label>Race</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
                <default>true</default>
                <label>Scheduled</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Red Flagged</fullName>
            </value>
            <value>
                <fullName>Finished</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RaceData__c/RaceData__c.object-meta.xml
<CustomObject>
    <label>Race Data</label>
    <nameField>
        <displayFormat>RDID-{0000000000}</displayFormat>
        <label>Race Data Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Race Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/fflib/RaceSelector.cls
/**
 * Created by Brooks Johnson - Insulet on 1/27/23.
 */

public with sharing class RaceSelector extends FormulaForceSelector {

    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField>{
                RaceData__c.Id,
                Race__c.Name,
                Race__c.Status__c
        };
    }

    public Schema.SObjectType getSObjectType() {
        return Race__c.SObjectType;
    }

    public List<Race__c> selectById(Set<Id> raceIds) {
        return (List<Race__c>) selectSObjectsById(raceIds);
    }

    public List<Race__c> selectByIdWithContestants(set<Id> raceIds){
        fflib_QueryFactory raceQueryFactory = newQueryFactory();
       fflib_QueryFactory contestQueryFactory = new ContestantSelector()
               .addQueryFactorySubselect(raceQueryFactory);
        return (List<Race__c>) Database.query(raceQueryFactory
                .setCondition('Id in : raceIds')
                .toSOQL());
    }
}