force-app/main/default/objects/Driver__c/Driver__c.object-meta.xml
<CustomObject>
    <label>Driver</label>
    <nameField>
        <label>Driver Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Drivers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Driver__c/fields/FIASuperLicense__c.field-meta.xml
<CustomField>
    <fullName>FIASuperLicense__c</fullName>
    <defaultValue>false</defaultValue>
    <label>FIA Super License</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/formula-force/DriversSelector.cls
/**
 * Created by Brooks Johnson - Insulet on 2/7/23.
 */

public inherited sharing class DriversSelector extends fflib_SObjectSelector {
    public   SObjectType getSObjectType() {
     return Driver__c.SObjectType;
    }

     public List<SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField>{
                Driver__c.Id,
                Driver__c.Name,
                Driver__c.FIASuperLicense__c,
                Driver__c.Team__c

        };
    }

    public List<Driver__c> selectByTeam(Set<Id> teamIds){
        return (List<Driver__c>) Database.query(newQueryFactory()
                .setCondition('Team__c in : teamIds')
                .toSOQL());
    }
}